#!/bin/bash

# Designed for Debian based OS

# This file is for installing Indaba Titan as part of a packaged build workflow (i.e. building a Raspberry PI image).

# DO NOT run this file at every boot as it will try to install Docker from the internet!

if [ -f ".titaninstalled" ]; then
  echo "Titan is already installed. To re-install, remove the .titaninstalled file in this directory."
  exit
fi

echo "This script installs Indaba Titan. If you do not wish to continue, press CTL-C now..."

sleep 5

# Install Docker:
echo "Installing Docker"

if [ -x "$(command -v docker)" ]; then
  echo "Docker already installed"
else
  curl -sSL https://get.docker.com | sh
  echo "Adding user to docker group"
  sudo usermod -aG docker $USER
fi

if docker image inspect bootlegger/titan-compact > /dev/null 2>&1 ; then
  echo "Image already installed"
else
  echo "Pulling Images to Local Cache"
  sudo docker pull bootlegger/titan-compact
fi

echo "Starting Titan"

MAC_ADDRESS=`ifconfig eth0 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}'`

sudo docker run --restart always --log-driver none -e sails_LOGINCODE=$MAC_ADDRESS --add-host=redis:127.0.0.1 --add-host=mongo:127.0.0.1 --add-host=beanstalk:127.0.0.1 --add-host=web:127.0.0.1 -p "80:88" -p "8845:80" -v "$(pwd)/upload:/usr/src/app/upload" bootlegger/titan-compact

echo "Marking as Installed"
touch .titaninstalled

exit