#!/bin/bash

# Designed for Debian based OS

# This file is for installing Indaba Titan as part of a packaged build workflow (i.e. building a Raspberry PI image).

# DO NOT run this file at every boot as it will try to install Docker from the internet!

if [ -f ".titaninstalled" ]; then
  echo "Titan is already installed. To re-install, remove the .titaninstalled file in this directory."
  exit
fi

echo "This script installs Indaba Titan. If you do not wish to continue, press CTL-C now..."

sleep 5

# Install Docker:
echo "Installing Docker"

if [ -x "$(command -v docker)" ]; then
  echo "Docker already installed"
else
  curl -sSL https://get.docker.com | sh
  echo "Adding user to docker group"
  sudo usermod -aG docker $USER
fi

if docker image inspect bootlegger/titan-compact > /dev/null 2>&1 ; then
  echo "Image already installed"
else
  echo "Pulling Images to Local Cache"
  sudo docker pull bootlegger/titan-compact
fi

if [ -f ".supervisorinstalled" ]; then

  echo "Installing Supervisor"

  echo "Downloading Supervisor"

  curl https://raw.githubusercontent.com/our-story-media/ourstory-titan/master/install/supervisor/build/indaba-supervisor -s -o indaba-supervisor

  echo "Changing Mode on Supervisor"

  chmod +x indaba-supervisor

  echo "Add supervisor to startup"

  echo "$(pwd)/indaba-supervisor & > $(pwd)/supervisor.log 2>&1" >> /etc/rc.local
  
  touch .supervisorinstalled

fi

echo "Starting Titan"

docker volume create indaba-db
docker volume create indaba-redis

MAC_ADDRESS=`ifconfig eth0 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}'`

sudo docker run --name indaba -d --restart always --log-driver local \
 -e sails_LOGINCODE=$MAC_ADDRESS \
 --add-host=redis:127.0.0.1 \
 --add-host=mongo:127.0.0.1 \
 --add-host=beanstalk:127.0.0.1 \
 --add-host=web:127.0.0.1 \
 -e sails_master_url="http://10.10.10.1:8845" \
 -e sails_FAKES3URL="http://10.10.10.1:8845/upload/" \
 -e sails_FAKES3URL_TRANSCODE="http://10.10.10.1:8845/upload/transcode/upload/" \
 -p "80:88" \
 -p "8845:80" \
 -v indaba-db:/data/db \
 -v indaba-redis:/etc/redis/database \
 -v "$(pwd)/upload:/usr/src/app/upload" \
 bootlegger/titan-compact

echo "Marking as Installed"

touch .titaninstalled

exit