//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bootlegger.App.Win.locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bootlegger.App.Win.locale.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Story requires additional components to be installed..
        /// </summary>
        public static string AdditionalComponents {
            get {
                return ResourceManager.GetString("AdditionalComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional downloads are required, please make sure you have internet connectivity before continuing.
        /// </summary>
        public static string AdditionalDownloads {
            get {
                return ResourceManager.GetString("AdditionalDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional software may need to be installed and take some additional time. Please be patient....
        /// </summary>
        public static string AdditionalSoftware {
            get {
                return ResourceManager.GetString("AdditionalSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Story Titan (en).
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Data.
        /// </summary>
        public static string BackupData {
            get {
                return ResourceManager.GetString("BackupData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Network settings and try again..
        /// </summary>
        public static string CheckNetworkSettingsAndTryAgain {
            get {
                return ResourceManager.GetString("CheckNetworkSettingsAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Application.
        /// </summary>
        public static string CloseApplication {
            get {
                return ResourceManager.GetString("CloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing this application will prevent access to Our Story.
        /// </summary>
        public static string CloseWarning {
            get {
                return ResourceManager.GetString("CloseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectivity.
        /// </summary>
        public static string Connectivity {
            get {
                return ResourceManager.GetString("Connectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Anyway.
        /// </summary>
        public static string ContinueAnyway {
            get {
                return ResourceManager.GetString("ContinueAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue?.
        /// </summary>
        public static string ContinueDialogTitle {
            get {
                return ResourceManager.GetString("ContinueDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docker Installer.
        /// </summary>
        public static string DockerInstaller {
            get {
                return ResourceManager.GetString("DockerInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Files.
        /// </summary>
        public static string DownloadFiles {
            get {
                return ResourceManager.GetString("DownloadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Content.
        /// </summary>
        public static string DownloadingContent {
            get {
                return ResourceManager.GetString("DownloadingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Docker Installer....
        /// </summary>
        public static string DownloadingDocker {
            get {
                return ResourceManager.GetString("DownloadingDocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0} of {1}.
        /// </summary>
        public static string DownloadingProgress {
            get {
                return ResourceManager.GetString("DownloadingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0} of {1}...\nThis may take some time....
        /// </summary>
        public static string DownloadWarning {
            get {
                return ResourceManager.GetString("DownloadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem installing Our Story. {0}. Please restart and try again..
        /// </summary>
        public static string ErrorDialog {
            get {
                return ResourceManager.GetString("ErrorDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiating Download....
        /// </summary>
        public static string InitiatingDownload {
            get {
                return ResourceManager.GetString("InitiatingDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Docker....
        /// </summary>
        public static string InstallingDocker {
            get {
                return ResourceManager.GetString("InstallingDocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Requirements.
        /// </summary>
        public static string InstallRequirements {
            get {
                return ResourceManager.GetString("InstallRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Network.
        /// </summary>
        public static string InvalidNetwork {
            get {
                return ResourceManager.GetString("InvalidNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate Images.tar file.
        /// </summary>
        public static string LoadImages {
            get {
                return ResourceManager.GetString("LoadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Our Story Components....
        /// </summary>
        public static string LoadingComponents {
            get {
                return ResourceManager.GetString("LoadingComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate the images.tar file that came with your installation files, or go online to download the remaining components..
        /// </summary>
        public static string LocateImages {
            get {
                return ResourceManager.GetString("LocateImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually Change Settings.
        /// </summary>
        public static string ManuallyChangeSettings {
            get {
                return ResourceManager.GetString("ManuallyChangeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Dashboard.
        /// </summary>
        public static string OpenDashboard {
            get {
                return ResourceManager.GetString("OpenDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Video Folder.
        /// </summary>
        public static string OpenFiles {
            get {
                return ResourceManager.GetString("OpenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Story Components.
        /// </summary>
        public static string OurStoryBits {
            get {
                return ResourceManager.GetString("OurStoryBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem starting application!.
        /// </summary>
        public static string ProblemStartingApplication {
            get {
                return ResourceManager.GetString("ProblemStartingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} of {2}.
        /// </summary>
        public static string ProgressLabel {
            get {
                return ResourceManager.GetString("ProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting Network....
        /// </summary>
        public static string ResettingNetwork {
            get {
                return ResourceManager.GetString("ResettingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Data.
        /// </summary>
        public static string RestoreData {
            get {
                return ResourceManager.GetString("RestoreData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable Sharing by doing the following:.
        /// </summary>
        public static string ShareWarning1 {
            get {
                return ResourceManager.GetString("ShareWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message will disappear when you have completed this step....
        /// </summary>
        public static string ShareWarning2 {
            get {
                return ResourceManager.GetString("ShareWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting....
        /// </summary>
        public static string starting {
            get {
                return ResourceManager.GetString("starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Application.
        /// </summary>
        public static string StartingApplication {
            get {
                return ResourceManager.GetString("StartingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Docker....
        /// </summary>
        public static string StartingDocker {
            get {
                return ResourceManager.GetString("StartingDocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping Application....
        /// </summary>
        public static string StoppingApplication {
            get {
                return ResourceManager.GetString("StoppingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Application.
        /// </summary>
        public static string UpdateApplication {
            get {
                return ResourceManager.GetString("UpdateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Our Story.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current WiFi settings are not correct..
        /// </summary>
        public static string WiFi {
            get {
                return ResourceManager.GetString("WiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you are connected to your deployment WiFi before continuing..
        /// </summary>
        public static string WiFi2 {
            get {
                return ResourceManager.GetString("WiFi2", resourceCulture);
            }
        }
    }
}
